name: 'Konnect Resources'
description: 'Provision or destroy Konnect resources'
inputs:
  konnect-resources:
    description: 'Path to the Konnect resources file'
    required: true
  action:
    description: 'Action to perform'
    required: true
    default: 'provision'
  vault-address:
    description: 'Vault address'
    required: false
    default: 'http://localhost:8300'
  vault-token:
    description: 'Vault token'
    required: true
  aws-endpoint-url:
    description: 'S3 endpoint URL'
    required: false
  aws-access-key-id:
    description: 'S3 access key'
    required: true
  aws-secret-access-key:
    description: 'S3 secret key'
    required: true
  aws-session-token:
    description: 'S3 session token'
    required: false
  aws-region:
    description: 'AWS region for S3'
    required: false
    default: 'eu-central-1'
  konnect-region:
    description: "Konnect region"
    required: false
    default: "eu"
  konnect-token:
    description: 'Konnect API token'
    required: true
  konnect-team-name:
    description: 'Team name to provision resources for'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 'latest'

    - name: Validate config
      shell: bash
      run: |
        ${{ github.action_path }}/scripts/validate-config.sh "${{ inputs.config }}"

    - name: Setup Terraform Environment
      shell: bash
      run: |

        # Set Vault environment variables
        echo "VAULT_ADDR=${{ inputs.vault-address }}" >> $GITHUB_ENV
        echo "vault-token=${{ inputs.vault-token }}" >> $GITHUB_ENV

        # Set AWS environment variables
        echo "AWS_ENDPOINT_URL=${{ inputs.aws-endpoint-url }}" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ inputs.aws-access-key-id }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ inputs.aws-secret-access-key }}" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=${{ inputs.aws-session-token }}" >> $GITHUB_ENV
        echo "AWS_REGION=${{ inputs.aws-region }}" >> $GITHUB_ENV

        # Set Konnect environment variables
        echo "TF_VAR_konnect_server_url=https://${{ inputs.konnect-region }}.api.konghq.com" >> $GITHUB_ENV
        echo "TF_VAR_konnect_access_token=${{ inputs.konnect-token }}" >> $GITHUB_ENV

        # Set other Terraform variables
        echo "TF_VAR_konnect_resources=${{ inputs.konnect-resources }}" >> $GITHUB_ENV
        echo "TF_VAR_gh_workspace_path=${{ github.workspace }}" >> $GITHUB_ENV
        echo "TF_VAR_team_name=${{ inputs.konnect-team-name }}" >> $GITHUB_ENV

    - name: Terraform Init
      shell: bash
      run: |
        terraform init -upgrade \
          -backend-config=config.s3.tfbackend \
          -backend-config="bucket=kw.konnect.team.resources.${{ inputs.konnect-team-name }}" \
          -backend-config="key=tfstate" \
          -backend-config="region=${{ inputs.aws-region }}"
      working-directory: ${{ github.action_path }}/terraform

    - name: Terraform Plan
      shell: bash
      if: ${{ inputs.action == 'provision' }}
      run: |
        terraform plan -out=tfplan
      working-directory: ${{ github.action_path }}/terraform

    - name: Terraform Apply
      shell: bash
      if: ${{ inputs.action == 'provision' }}
      id: tfapply
      run: |
        terraform apply -auto-approve tfplan
      working-directory: ${{ github.action_path }}/terraform

    - name: Terraform destroy
      shell: bash
      if: ${{ inputs.action == 'destroy' }}
      run: |
        terraform destroy -auto-approve
      working-directory: ${{ github.action_path }}/terraform
