name: Onboard Konnect Teams

on:
  workflow_dispatch:
    inputs:
      kong-image-repo:
        description: Kong image repository (e.g., kong/kong-gateway)
        required: true
        default: kong/kong-gateway
      kong-image-tag:
        description: Kong image tag (e.g., 3.8)
        required: true
        default: "3.8"
      environment:
        description: Deployment environment (e.g., dev, staging, prod)
        required: false
        default: dev

env:
  TF_VAR_resources_path: ${{ github.workspace }}/teams
  TERRAFORM_DIR: ${{ github.workspace }}/terraform/konnect-teams

jobs:
  deploy-dataplane:
    runs-on: ubuntu-latest
    env:
      # Hashicorp Vault related variables
      # Used for configuring TF Vault provider
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ env.VAULT_TOKEN }}
          secrets: |
            ${{ vars.KONNECT_TEAM_NAME }}-kv/data/control-planes/${{ vars.KONNECT_TEAM_NAME }}-${{ inputs.environment }} clustering_cert | CP_CLUSTERING_CERT ;
            ${{ vars.KONNECT_TEAM_NAME }}-kv/data/control-planes/${{ vars.KONNECT_TEAM_NAME }}-${{ inputs.environment }} clustering_cert_key | CP_CLUSTERING_CERT_KEY ;
            ${{ vars.KONNECT_TEAM_NAME }}-kv/data/control-planes/${{ vars.KONNECT_TEAM_NAME }}-${{ inputs.environment }} control_plane_endpoint | CP_ENDPOINT ;
            ${{ vars.KONNECT_TEAM_NAME }}-kv/data/control-planes/${{ vars.KONNECT_TEAM_NAME }}-${{ inputs.environment }} telemetry_endpoint | CP_TELEMETRY_ENDPOINT ;
            ${{ vars.KONNECT_TEAM_NAME }}-kv/data/control-planes/${{ vars.KONNECT_TEAM_NAME }}-${{ inputs.environment }} name | CP_NAME ;

      - name: Deploy Data Plane
        uses: ./.github/actions/deploy-dp
        with:
          kong-image-repo: ${{ inputs.kong-image-repo || 'kong/kong-gateway' }}
          kong-image-tag: ${{ inputs.kong-image-tag || '3.11' }}
          team-name: "flight-operations"
          control-plane-clustering-cert: $CP_CLUSTERING_CERT
          control-plane-clustering-cert-key: $CP_CLUSTERING_CERT_KEY
          control-plane-endpoint: $CP_ENDPOINT
          telemetry-endpoint: $CP_TELEMETRY_ENDPOINT
          control-plane-name: $CP_NAME
          environment: ${{ inputs.environment  }}
          kube-context: ${{ secrets.KUBE_CONTEXT }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          cluster-name: "konnect-301-eks-wDoLaiGY"
