name: Onboard Konnect Teams

on:
  workflow_dispatch:
    inputs:
      kong_image_repo:
        description: Kong image repository (e.g., kong/kong-gateway)
        required: true
        default: kong/kong-gateway
      kong_image_tag:
        description: Kong image tag (e.g., 3.8)
        required: true
        default: "3.8"

env:
  TF_VAR_resources_path: ${{ github.workspace }}/teams
  TERRAFORM_DIR: ${{ github.workspace }}/terraform/konnect-teams

jobs:
  deploy-dataplane:
    runs-on: ubuntu-latest
    env:
      # Hashicorp Vault related variables
      # Used for configuring TF Vault provider
      VAULT_ADDR: ${{ vars.VAULT_ADDR }}
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Data Plane
        uses: ./.github/actions/deploy-dp
        with:
          kong_image_repo: ${{ inputs.kong_image_repo || 'kong/kong-gateway' }}
          kong_image_tag: ${{ inputs.kong_image_tag || '3.11' }}
          team-name: "flight-operations"
          environment: "dev"